server:
  port: 8081
spring:
  application:
    name: library
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 1012
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      # redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  cache:
    redis:
      time-to-live: 1800000

mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.ljc.librarybackend.pojo.entity
  mapper-locations: classpath:com/ljc/librarybackend/mapper/xml/*.xml

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5t8V4nkWZ8J5qAe3Wm79
    keySecret: eKZr2HSgF9j7CRBbHnKlDG2334f4Zl
    bucketName: srb-file-liang